/* tslint:disable */
/* eslint-disable */
/**
 * Story Generator
 * The story generator API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChapterDto
 */
export interface ChapterDto {
    /**
     * ID of the chapter
     * @type {number}
     * @memberof ChapterDto
     */
    'id'?: number;
    /**
     * Number of the chapter
     * @type {number}
     * @memberof ChapterDto
     */
    'number'?: number;
    /**
     * Title of the chapter
     * @type {string}
     * @memberof ChapterDto
     */
    'title': string;
    /**
     * Summary of the chapter
     * @type {string}
     * @memberof ChapterDto
     */
    'summary': string;
    /**
     * Content of the chapter
     * @type {string}
     * @memberof ChapterDto
     */
    'content'?: string;
    /**
     * Audio URL of the chapter
     * @type {string}
     * @memberof ChapterDto
     */
    'audio_url'?: string;
    /**
     * Video URL of the chapter
     * @type {string}
     * @memberof ChapterDto
     */
    'video_url'?: string;
    /**
     * Background sound for the chapter
     * @type {string}
     * @memberof ChapterDto
     */
    'background_sound'?: string;
    /**
     * ID of the story this chapter belongs to
     * @type {number}
     * @memberof ChapterDto
     */
    'story_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ChapterDto
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof ChapterDto
     */
    'updated_at'?: string;
}

