/* tslint:disable */
/* eslint-disable */
/**
 * Story Generator
 * The story generator API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ChapterDto
 */
export interface ChapterDto {
    /**
     * 
     * @type {number}
     * @memberof ChapterDto
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof ChapterDto
     */
    'number': number;
    /**
     * 
     * @type {string}
     * @memberof ChapterDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ChapterDto
     */
    'summary': string;
    /**
     * 
     * @type {string}
     * @memberof ChapterDto
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof ChapterDto
     */
    'background_sound': string;
    /**
     * 
     * @type {string}
     * @memberof ChapterDto
     */
    'audio_url': string;
    /**
     * 
     * @type {string}
     * @memberof ChapterDto
     */
    'video_url': string;
    /**
     * 
     * @type {number}
     * @memberof ChapterDto
     */
    'stories_id': number;
}

