/* tslint:disable */
/* eslint-disable */
/**
 * Story Generator
 * The story generator API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateStoryDto
 */
export interface CreateStoryDto {
    /**
     * Type id of the story
     * @type {number}
     * @memberof CreateStoryDto
     */
    'types_id': number;
}

