/* tslint:disable */
/* eslint-disable */
/**
 * Story Generator
 * The story generator API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PublishingDto
 */
export interface PublishingDto {
    /**
     * 
     * @type {number}
     * @memberof PublishingDto
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof PublishingDto
     */
    'story_id': number;
    /**
     * 
     * @type {string}
     * @memberof PublishingDto
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof PublishingDto
     */
    'description': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PublishingDto
     */
    'tags': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PublishingDto
     */
    'youtube_id': string;
    /**
     * 
     * @type {boolean}
     * @memberof PublishingDto
     */
    'patreon_published': boolean;
}

