/* tslint:disable */
/* eslint-disable */
/**
 * Story Generator
 * The story generator API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TypeDto
 */
export interface TypeDto {
    /**
     * 
     * @type {number}
     * @memberof TypeDto
     */
    'id': number;
    /**
     * Type of the story
     * @type {string}
     * @memberof TypeDto
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof TypeDto
     */
    'story_prompt': string;
    /**
     * 
     * @type {string}
     * @memberof TypeDto
     */
    'chapter_prompt': string;
    /**
     * 
     * @type {string}
     * @memberof TypeDto
     */
    'image_prompt': string;
    /**
     * 
     * @type {string}
     * @memberof TypeDto
     */
    'sound_prompt': string;
    /**
     * 
     * @type {string}
     * @memberof TypeDto
     */
    'youtube_channel_id': string;
    /**
     * 
     * @type {string}
     * @memberof TypeDto
     */
    'youtube_playlist_id': string;
}

