/* tslint:disable */
/* eslint-disable */
/**
 * Story Generator
 * The story generator API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TypeDto
 */
export interface TypeDto {
    /**
     * 
     * @type {number}
     * @memberof TypeDto
     */
    'id': number;
    /**
     * Type of the story
     * @type {string}
     * @memberof TypeDto
     */
    'name': string;
    /**
     * Story prompt
     * @type {string}
     * @memberof TypeDto
     */
    'story_prompt': string;
    /**
     * Chapter prompt
     * @type {string}
     * @memberof TypeDto
     */
    'chapter_prompt': string;
    /**
     * Image prompt
     * @type {string}
     * @memberof TypeDto
     */
    'image_prompt': string;
    /**
     * Sound prompt
     * @type {string}
     * @memberof TypeDto
     */
    'sound_prompt': string;
    /**
     * Youtube channel ID
     * @type {string}
     * @memberof TypeDto
     */
    'youtube_channel_id': string;
    /**
     * Youtube playlist ID
     * @type {string}
     * @memberof TypeDto
     */
    'youtube_playlist_id': string;
    /**
     * Number of chapters to generate
     * @type {number}
     * @memberof TypeDto
     */
    'chapter_count': number;
    /**
     * Minimum word count for the story
     * @type {number}
     * @memberof TypeDto
     */
    'word_count': number;
}

